// COS — DEMO data. A fully fictional founder ("Sam Reyes") and workspace, used
// only in the public read-only demo (see session.ts). Deliberately unrelated to
// the real account so nothing real is ever exposed. Same COSData shape as the
// real set, so every screen renders identically.
import type { COSData } from "./types";

export const DEMO_DATA: COSData = {
  user: { name: "Sam Reyes", initials: "SR", greetingName: "Sam" },
  doorway: {
    motto: "Build the calm thing. Ship it. Tend it.",
    quotes: [
      { t: "The best way to predict the future is to invent it.", who: "Alan Kay", role: "Computer scientist" },
      { t: "Make something people want.", who: "Paul Graham", role: "Y Combinator" },
      { t: "Simplicity is the ultimate sophistication.", who: "Leonardo da Vinci", role: "Polymath" },
      { t: "Done is better than perfect.", who: "Sheryl Sandberg", role: "Operator" },
      { t: "Real artists ship.", who: "Steve Jobs", role: "Apple" },
      { t: "Slow is smooth, smooth is fast.", who: "Proverb", role: "—" },
    ],
  },
  today: {
    date: "Tuesday, June 9",
    calendar: "Sample · Demo Calendar",
    blocks: [
      { start: "9:00", end: "9:30", title: "Morning re-entry", kind: "ritual", proj: null,
        walkIn: "Plan the day. COS lays out where you left off across every project." },
      { start: "9:30", end: "11:00", title: "Polish the reader view", kind: "focus", proj: "lantern",
        walkIn: "Typography pass on the reader — the spec is open at the spacing notes." },
      { start: "11:30", end: "12:00", title: "Sync with Mara — beta invites", kind: "meeting", proj: "tidepool", who: "Mara Quinn",
        walkIn: "Decide how many beta seats to open this week. Bring the waitlist numbers." },
      { start: "1:30", end: "2:30", title: "Write the launch note", kind: "focus", proj: "tidepool",
        walkIn: "Short note for the first 50 makers — warm, specific, no hype." },
      { start: "3:00", end: "3:30", title: "Reply to roaster quotes", kind: "focus", proj: "cafe",
        walkIn: "Three roasters sent pricing — pick one and lock the house blend." },
    ],
  },
  projects: [
    {
      id: "lantern", name: "Lantern", accent: "mint", status: "in-motion",
      why: "A calm reading app that turns saved articles into a quiet nightly shelf.",
      focus: "Getting the reader typography right before the TestFlight build.",
      lastActivity: "yesterday", lastVerb: "tuning the reader typography", away: "1 day",
      progress: [
        "Shipped the save-from-share-sheet flow",
        "Built the nightly shelf that resurfaces 3 reads",
        "Settled on a single serif for long-form",
      ],
      blockers: [],
      openQuestions: ["Do we sync across devices in v1, or stay local?"],
      openDecisions: ["Free with a Pro tier, or one flat price?"],
      nextAction: "Finish the typography pass, then cut the TestFlight build.",
      due: "Jun 24", lastMovement: "Settled on a single serif for long-form",
      notes: ["Calm over clever — no streaks, no badges.", "The shelf is the product. Protect it."],
      research: [
        { t: "Read-later abandonment", d: "Most saved articles are never reopened — resurfacing is the real job." },
        { t: "Reading retention", d: "A small nightly set beats an endless inbox of saves." },
      ],
      ideasFlow: [
        { name: "Shared shelves", stage: "Spark" },
        { name: "Audio reader", stage: "Brewing" },
      ],
      pct: 65,
      resume: [
        { kind: "Spec", t: "Reader typography — spacing + serif", when: "yesterday" },
        { kind: "Build", t: "Nightly shelf resurfacing logic", when: "3 days ago" },
      ],
      counts: { ideas: 2, research: 5, knowledge: 4, files: 9, people: 2, decisions: 2, timeline: 14 },
      decisionsList: [
        { t: "No streaks, ever", d: "Pressure breaks the calm. The shelf invites, it never nags.", when: "1 week ago" },
        { t: "Local-first storage", d: "Your reads stay on your device by default.", when: "2 weeks ago" },
      ],
      knowledgeList: [
        { t: "Resurfacing beats collecting", d: "The value isn't saving — it's bringing the right read back.", used: "Lantern" },
        { t: "Calm is a feature", d: "Removing pressure is design work, not the absence of it.", used: "Lantern" },
      ],
      peopleList: [
        { n: "Mara Quinn", r: "Design partner · product", initials: "MQ" },
        { n: "Devon Park", r: "iOS contractor", initials: "DP" },
      ],
    },
    {
      id: "tidepool", name: "Tidepool", accent: "violet", status: "in-motion",
      why: "A small, slow community where makers share works-in-progress, not highlight reels.",
      focus: "Opening the first wave of beta invites without breaking the calm.",
      lastActivity: "2 days ago", lastVerb: "drafting the launch note", away: "2 days",
      progress: [
        "Built the weekly 'what are you making?' prompt",
        "Capped rooms at 12 to keep it intimate",
        "Wrote the community guidelines",
      ],
      blockers: ["Need the waitlist export before sizing the first wave"],
      openQuestions: ["Invite-only forever, or open after the first season?"],
      openDecisions: ["How many seats to open in wave one"],
      nextAction: "Finish the launch note, then send the first 50 invites.",
      due: "Jun 16", lastMovement: "Wrote the community guidelines",
      notes: ["Small on purpose. Growth is the enemy here.", "Works-in-progress only — no launches, no flexing."],
      research: [
        { t: "Community size vs. warmth", d: "Intimacy drops sharply past a few dozen active members." },
      ],
      ideasFlow: [
        { name: "Seasonal cohorts", stage: "Brewing" },
      ],
      pct: 45,
      resume: [
        { kind: "Draft", t: "Launch note for the first 50", when: "2 days ago" },
        { kind: "Doc", t: "Community guidelines v1", when: "4 days ago" },
      ],
      counts: { ideas: 1, research: 3, knowledge: 3, files: 6, people: 3, decisions: 2, timeline: 11 },
      decisionsList: [
        { t: "Rooms cap at 12", d: "Intimacy over reach. Smallness is the whole point.", when: "5 days ago" },
        { t: "WIP only", d: "No finished launches. The mess is what bonds people.", when: "1 week ago" },
      ],
      knowledgeList: [
        { t: "Warmth doesn't scale", d: "The thing people love breaks the moment it gets big.", used: "Tidepool" },
        { t: "Constraints make culture", d: "The cap and the prompt do more than any rulebook.", used: "Tidepool" },
      ],
      peopleList: [
        { n: "Mara Quinn", r: "Co-host · community", initials: "MQ" },
        { n: "Leah Osei", r: "First beta member", initials: "LO" },
        { n: "Theo Brandt", r: "First beta member", initials: "TB" },
      ],
    },
    {
      id: "cafe", name: "Corner Café", accent: "amber", status: "dormant",
      why: "A tiny neighborhood coffee bar — a tangible counterweight to a life made of screens.",
      focus: "Deciding whether this is a real plan or a beloved daydream.",
      lastActivity: "3 weeks ago", lastVerb: "pricing out roasters", away: "3 weeks",
      progress: [
        "Toured two possible storefronts",
        "Got pricing from three roasters",
      ],
      blockers: [],
      openQuestions: ["Would I actually run it, or just romanticize it?"],
      openDecisions: ["House blend roaster", "Real plan, or daydream?"],
      nextAction: "Pick a roaster, then honestly decide if this is happening.",
      due: null, lastMovement: "Got pricing from three roasters",
      notes: ["Don't let this drift forever — decide by fall.", "If it happens, calm and small, like everything else."],
      research: [
        { t: "Small café economics", d: "Rent and labor decide it long before the coffee does." },
      ],
      ideasFlow: [],
      pct: 20,
      resume: [
        { kind: "Note", t: "Roaster pricing — three quotes", when: "3 weeks ago" },
      ],
      counts: { ideas: 0, research: 2, knowledge: 1, files: 4, people: 1, decisions: 1, timeline: 6 },
      decisionsList: [
        { t: "Neighborhood, not destination", d: "A corner regulars trust beats a place people travel to.", when: "3 weeks ago" },
      ],
      knowledgeList: [
        { t: "Tangible counterweight", d: "Hands-on work resets a screen-heavy mind.", used: "Corner Café" },
      ],
      peopleList: [
        { n: "Gabe Flores", r: "Roaster · house blend", initials: "GF" },
      ],
    },
  ],
  ideas: [
    { id: "shelves", name: "Shared Shelves", stage: "Brewing", why: "Let two people keep a reading shelf together — quietly, no feed.",
      heat: "Warm", heatNote: "Came up three times this week with beta readers.",
      questions: ["Part of Lantern, or its own thing?", "Two people only, or small groups?"],
      related: ["Lantern"], lastActivity: "3 days ago", lastMove: "Sketched the shared-shelf invite flow",
      spark: "A friend asked to swap reading lists and there was no calm way to do it.",
      nextMove: "Mock the two-person shelf and test it with Mara." },
    { id: "seasons", name: "Seasonal Cohorts", stage: "Exploring", why: "Run Tidepool in 6-week seasons instead of an always-on feed.",
      heat: "Warm", heatNote: "Keeps surfacing in community planning.",
      questions: ["Does the room close between seasons, or just rest?", "Six weeks, or eight?"],
      related: ["Tidepool"], lastActivity: "6 days ago", lastMove: "Outlined a single season arc",
      spark: "Always-on communities burn out; seasons give a natural beginning and end.",
      nextMove: "Draft what one season actually looks like, week by week." },
    { id: "audio", name: "Audio Reader", stage: "Spark", why: "Read the nightly shelf aloud for walks and commutes.",
      heat: "Cooling", heatNote: "No movement in 9 days.",
      questions: ["On-device voice, or cloud?", "A v1 feature, or a v2 distraction?"],
      related: ["Lantern"], lastActivity: "9 days ago", lastMove: "Noted it as a maybe-later",
      spark: "Wanted the shelf on a morning walk without staring at a screen.",
      nextMove: "Park it until the reader ships — revisit then." },
  ],
  sparks: ["Reading retreats", "A zine about slow software", "Café + Tidepool meetup", "Letterpress shelf tags", "A calm-tech reading list"],
  activity: [
    { proj: "Lantern", accent: "mint", verb: "Tuned", what: "the reader typography", when: "yesterday" },
    { proj: "Tidepool", accent: "violet", verb: "Drafted", what: "the launch note", when: "2 days ago" },
    { proj: "Lantern", accent: "mint", verb: "Built", what: "the nightly shelf logic", when: "3 days ago" },
    { proj: "Tidepool", accent: "violet", verb: "Wrote", what: "the community guidelines", when: "4 days ago" },
    { proj: "Corner Café", accent: "amber", verb: "Priced", what: "three roaster quotes", when: "3 weeks ago" },
  ],
  searchPeople: [
    { n: "Mara Quinn", r: "Design partner", proj: "Lantern", initials: "MQ" },
    { n: "Devon Park", r: "iOS contractor", proj: "Lantern", initials: "DP" },
    { n: "Leah Osei", r: "Beta member", proj: "Tidepool", initials: "LO" },
    { n: "Gabe Flores", r: "Roaster", proj: "Corner Café", initials: "GF" },
  ],
  searchKnowledge: [
    { t: "Resurfacing beats collecting", d: "The value is bringing the right read back.", used: "Lantern" },
    { t: "Warmth doesn't scale", d: "What people love breaks once it gets big.", used: "Tidepool" },
    { t: "Constraints make culture", d: "The cap and the prompt beat any rulebook.", used: "Tidepool" },
    { t: "Calm is a feature", d: "Removing pressure is real design work.", used: "Lantern" },
  ],
  searchDecisions: [
    { t: "No streaks, ever", used: "Lantern" },
    { t: "Rooms cap at 12", used: "Tidepool" },
    { t: "WIP only", used: "Tidepool" },
    { t: "Local-first storage", used: "Lantern" },
  ],
  lab: {
    agents: [
      { initials: "MS", name: "Market Scout", accent: "indigo", status: "field",
        assignment: "Watching the field — reading apps, calm tech, small-community tools.",
        finding: "Two read-later apps shipped AI summaries this week.",
        last: "3h ago" },
      { initials: "TK", name: "Thread Keeper", accent: "green", status: "reporting",
        assignment: "Watching relationships, quiet conversations, open loops.",
        finding: "Leah from the Tidepool beta hasn't heard back in 6 days.",
        last: "this morning" },
      { initials: "AR", name: "Archivist", accent: "amber", status: "field",
        assignment: "Tracking decisions, pivots, project history.",
        finding: "Lantern committed to local-first storage on June 2.",
        last: "yesterday" },
      { initials: "IG", name: "Idea Gardener", accent: "rose", status: "field",
        assignment: "Watching recurring thoughts and unfinished ideas.",
        finding: "Shared shelves has come up three times this week.",
        last: "2 days ago" },
      { initials: "FB", name: "Founder Briefing", accent: "violet", status: "reporting",
        assignment: "Preparing daily context for the start of your day.",
        finding: "Tidepool invites are ready to send. Lantern typography is the last gate before TestFlight.",
        last: "just now" },
      { initials: "CC", name: "Context Cartographer", accent: "teal", status: "field",
        assignment: "Mapping connections between projects, ideas, and decisions.",
        finding: "'Calm' shows up across Lantern, Tidepool, and Corner Café.",
        last: "5h ago" },
    ],
    experiments: [
      { name: "Nightly Shelf", accent: "rose", state: "active",
        q: "Can a small nightly set get people to actually read what they save?",
        note: "Testing 3 resurfaced reads a night against an open list." },
      { name: "Season One", accent: "amber", state: "active",
        q: "Does running Tidepool in seasons keep it warmer than always-on?",
        note: "Planning a single 6-week arc to try with the first cohort." },
      { name: "Quiet Onboarding", accent: "indigo", state: "paused",
        q: "Can new members feel at home without a tour or a feed?",
        note: "Paused until the first wave of invites goes out." },
    ],
    shelves: [
      { name: "Calm Tech", accent: "indigo", count: 24, sample: "Latest: removing pressure as design work" },
      { name: "Reading", accent: "green", count: 31, sample: "Latest: read-later abandonment studies" },
      { name: "Community", accent: "blue", count: 18, sample: "Latest: why warmth stops scaling" },
      { name: "Typography", accent: "violet", count: 14, sample: "Latest: serifs for long-form on screens" },
      { name: "Small Business", accent: "amber", count: 9, sample: "Latest: tiny café unit economics" },
      { name: "Product", accent: "teal", count: 16, sample: "Latest: the shelf is the product" },
    ],
    reports: [
      { t: "What Has Your Attention?", kind: "Attention Audit", when: "today", fresh: true,
        d: "The people, projects, and ideas using most of your bandwidth right now." },
      { t: "What Changed This Week?", kind: "Change Log", when: "Friday", fresh: true,
        d: "Decisions, pivots, completed work, and new directions." },
      { t: "Things You Keep Coming Back To", kind: "Recurrence Analysis", when: "weekly", fresh: true,
        d: "Ideas and concerns repeatedly appearing across your work." },
      { t: "Connections You May Be Missing", kind: "Context Mapping", when: "weekly", fresh: false,
        d: "Projects, ideas, and people that keep quietly intersecting." },
      { t: "Projects Losing Momentum", kind: "Momentum Check", when: "3 days ago", fresh: false,
        d: "What's drifting toward dormant — before it goes quiet." },
      { t: "This Week in the Lab", kind: "Weekly Findings", when: "Mon 8am", fresh: false,
        d: "Everything the agents brought back this week, in one read." },
    ],
  },
};
